/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "primary-container": "#6d00df",
        "primary-fixed": "#eaddff",
        "on-tertiary-fixed-variant": "#005313",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#83e881",
        "primary": "#a32cc4",
        "inverse-primary": "#d0bcff",
        "on-background": "#191c1e",
        "secondary": "#466270",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#00105c",
        "surface-container-low": "#f2f4f6",
        "surface-bright": "#f8f9fb",
        "surface-tint": "#a32cc4",
        "tertiary": "#004e11",
        "surface-dim": "#d8dadc",
        "on-secondary-container": "#4a6774",
        "tertiary-container": "#00691b",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#293ca0",
        "error": "#ba1a1a",
        "on-primary-container": "#cacfff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "background": "#f8fafc",
        "outline-variant": "#c5c5d4",
        "outline": "#757684",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#bac3ff",
        "on-surface-variant": "#454652",
        "secondary-fixed-dim": "#adcbda",
        "on-secondary-fixed": "#001f2a",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#94f990",
        "on-tertiary-fixed": "#002204",
        "surface-container": "#eceef0",
        "secondary-container": "#c6e4f4",
        "on-secondary-fixed-variant": "#2e4b57",
        "surface": "#f8fafc",
        "secondary-fixed": "#c9e7f7",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#78dc77"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
